#!/usr/bin/sh

# Usage:
#   inr [OPTIONS] FILE COMMAND
#
# Author: Prajjwal Bhandari

file_name=$1
shift

while true; do
  change=$(inotifywait -e modify,close_write,moved_to,create $file_name)
  eval $@
done
